export const projectsPortuguese = [
  {
    id: 1,
    category: "WEB",
    title: "DevLinks",
    description:
      "Agregador de links para você utilizar como cartão de visitas online",
    imgURL: "./assets/projects/devlinks.png",
    stacks: ["JavaScript", "HTML", "CSS"],
    link: "https://lgustta13.github.io/devlinks/",
    github: "https://github.com/LGustta13/devlinks",
  },
  {
    id: 2,
    category: "WEB",
    title: "DTMoney",
    description: "Plataforma para seu controle de gastos",
    imgURL: "./assets/projects/dtmoney.png",
    stacks: ["JavaScript", "HTML", "CSS", "Styled Components"],
    link: "https://dtmoney-lgusta.vercel.app/",
    github: "https://github.com/LGustta13/dtmoney",
  },
  {
    id: 3,
    category: "WEB",
    title: "Monitore IoT",
    description:
      "Plataforma de monitoramento de dados de telemetria desenvolvido durante meu TCC",
    imgURL: "./assets/projects/monitore.png",
    stacks: ["JavaScript", "React", "TypeScript", "ApexCharts", "CSS"],
    link: "https://monitore-iot-lgusta.vercel.app/",
    github: "https://github.com/LGustta13/monitore_iot/tree/master/web-vite",
  },
  {
    id: 4,
    category: "WEB",
    title: "Time Traveller",
    description: "Registre seus melhores momentos e memórias",
    imgURL: "./assets/projects/timetraveller.png",
    stacks: ["Next", "React", "TypeScript", "TailwindCSS", "Fastify", "Prisma"],
    link: "https://traveller-lgusta.vercel.app/",
    github: "https://github.com/LGustta13/time_traveller",
  },
  {
    id: 5,
    category: "MOBILE",
    title: "My Skills",
    description: "Registre suas habilidades durante seus estudos",
    imgURL: "./assets/projects/myskills.png",
    stacks: ["Next", "React", "TypeScript", "TailwindCSS", "Fastify", "Prisma"],
    link: "#",
    github: "https://github.com/LGustta13/devlinks",
  },
  {
    id: 6,
    category: "WEB",
    title: "Login page",
    description:
      "Tenha um template de página de login com design system e documentação",
    imgURL: "./assets/projects/loginpage.png",
    stacks: ["React", "TailwindCSS"],
    link: "https://login-page-lgusta.vercel.app/",
    github: "https://github.com/LGustta13/login-page",
  },
]

export const projectsEnglish = [
  {
    id: 1,
    category: "WEB",
    title: "DevLinks",
    description: "Link aggregator for you to use as an online business card",
    imgURL: "./assets/projects/devlinks.png",
    stacks: ["JavaScript", "HTML", "CSS"],
    link: "https://lgustta13.github.io/devlinks/",
    github: "https://github.com/LGustta13/devlinks",
  },
  {
    id: 2,
    category: "WEB",
    title: "DTMoney",
    description: "Platform for your expense control",
    imgURL: "./assets/projects/dtmoney.png",
    stacks: ["JavaScript", "HTML", "CSS", "Styled Components"],
    link: "https://dtmoney-lgusta.vercel.app/",
    github: "https://github.com/LGustta13/dtmoney",
  },
  {
    id: 3,
    category: "WEB",
    title: "Monitore IoT",
    description:
      "Telemetry data monitoring platform developed during my undergraduate thesis",
    imgURL: "./assets/projects/monitore.png",
    stacks: ["JavaScript", "React", "TypeScript", "ApexCharts", "CSS"],
    link: "https://monitore-iot-lgusta.vercel.app/",
    github: "https://github.com/LGustta13/monitore_iot/tree/master/web-vite",
  },
  {
    id: 4,
    category: "WEB",
    title: "Time Traveller",
    description: "Record your best moments and memories",
    imgURL: "./assets/projects/timetraveller.png",
    stacks: ["Next", "React", "TypeScript", "TailwindCSS", "Fastify", "Prisma"],
    link: "https://traveller-lgusta.vercel.app/",
    github: "https://github.com/LGustta13/time_traveller",
  },
  {
    id: 5,
    category: "MOBILE",
    title: "My Skills",
    description: "Document your skills during your studies",
    imgURL: "./assets/projects/myskills.png",
    stacks: ["Next", "React", "TypeScript", "TailwindCSS", "Fastify", "Prisma"],
    link: "#",
    github: "https://github.com/LGustta13/devlinks",
  },
  {
    id: 6,
    category: "WEB",
    title: "Login page",
    description:
      "Get a login page template with a design system and documentation",
    imgURL: "./assets/projects/loginpage.png",
    stacks: ["React", "TailwindCSS"],
    link: "https://login-page-lgusta.vercel.app/",
    github: "https://github.com/LGustta13/login-page",
  },
]
